# Docker 
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

    - bash: |
        npm i -g snyk
        snyk auth "$SNYK_TOKEN"
        snyk container test "$(imageName):$(tag)" --file="$(Build.SourcesDirectory)/Dockerfile" --severity-threshold=high
      displayName: 'Snyk: scan container image'
      env:
        SNYK_TOKEN: $(ci-azuredevops-juice-shop-open-sourcecode)
